swagger: '2.0'
info:
  version: '0.1'
  title: Home API
  description: An api to add smart devices to your home and control them
#host: ????
basePath: /dev
schemes:
  - https
security:
  - api_key: []
paths:
  /rooms:
    post:
      description: Adds a new room to your home
      security:
        - api_key: []
      x-amazon-apigateway-request-validator: all
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: name
          description: Name of room to be added to the home
          type: string
      responses:
        200:
          description: A room
          schema:
            $ref: '#/definitions/Room'
        400:
          description: Error
          schema:
            $ref: '#/definitions/Error'
      x-lambda-function: create-room
    get:
      description: Gets a list of all rooms in your home
      security:
        - api_key: []
      produces:
        - application/json
      responses:
        200:
          description: A list of rooms
          schema:
            type: array
            items:
              $ref: '#/definitions/Room'
        400:
          description: Error
          schema:
            $ref: '#/definitions/Error'
      x-lambda-function: get-rooms
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
#Object Definitions
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Room:
    description: A room is a way to organize devices in your home api.
    type: object
    properties:
      room_id:
        type: string
        description: Unique identifier attached to the room.
      name:
        type: string
        description: Name of the room
#Request Validators
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: true
    validateRequestParameters: true
  
x-lambda-functions: 
  create-room:
    runtime: python3.6
    handler: create_room.lambda_handler
    memory: 128
    path_to_code: ./rooms
  get-rooms:
    runtime: python3.6
    handler: get_rooms.lambda_handler
    memory: 128
    path_to_code: ./rooms