swagger: '2.0'
info:
  version: '1.0'
  title: Home API
  description: An api to add smart devices to your home and control them
#host: ????
basePath: /dev
schemes:
  - https
security:
  - api_key: []
paths:
  /rooms:
    post:
      description: Adds a new room to your home
      security:
        - api_key: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: name
          description: Name of room to be added to the home
          type: string
      x-lambda-function: create-room
      responses:
        200:
          description: A room
          schema:
            $ref: '#/definitions/Room'
        400:
          description: Error
          schema:
            $ref: '#/definitions/Error'
    get:
      description: Gets a list of all rooms in your home
      security:
        - api_key: []
      produces:
        - application/json
      responses:
        200:
          description: A list of rooms
          schema:
            type: array
            items:
              $ref: '#/definitions/Room'
        400:
          description: Error
      x-lambda-function: get-rooms

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header


definitions:
  Error:
    description: Error Message
    properties:
      errorMessage:
        type: string
        description: Description of the error message.
  Room:
    description: A room is a way to organize devices in your home api.
    type: object
    properties:
      room_id:
        type: string
        description: Unique identifier attached to the room.
      name:
        type: string
        description: Name of the room

#Lambda Functions
  
x-lambda-functions: 
  create-room:
    runtime: python3.6
    handler: create_room.lambda_handler
    memory: 128
    path_to_code: ./rooms
  get-rooms:
    runtime: python3.6
    handler: get_rooms.lambda_handler
    memory: 128
    path_to_code: ./rooms